### ISSUE TITLE
iptables script

### ISSUE THREAD

**Issue by pgorod** [opustecnica/public#1]
Hi @opustecnica! First of all, let me thank you for this script here:
https://github.com/opustecnica/public/wiki/UDM-&-UDM-PRO-NOTES

I have a question about it, if you don't mind... in the "to-do" you say that you need to adapt it to run with **`sh`** instead of **`bash`**... actually I am getting this problem. When I SSH into my UDM, I get an environment where

1. I have **`iptables`** and I see my firewall rule set, but
2. I don't have **`bash`**, just **`sh`**, which is making it difficult to use scripts from the Internet because they are usually **`bash`**

On the other hand, if I go into **`unifi-os shell`**, I get
1. A nice environment with **`bash`** available, but
2. It doesn't seem to know anything about **`iptables`**... :-(

I've searched a bit around the web but I couldn't get much information on this **`unifi-os shell`**, what is it anyway? A container, a chroot, what?

Anyway, I digress - my question to you is: what about your script doesn't work in **`sh`**? Did you ever make a **`sh`** version of it? I am afraid I am not fluent in shell scripting (any kind), so I'd appreciate your help. Thanks!

**Comment by opustecnica** [comment]
@pgorod,  the UDM architecture includes a "booting" OS/Distro and the unifi-os as a container.  While the first contains the binaries that allow the device to be a firewall (e.g. iptables), the container (unifi-os) handles the interface (GUI) you use to interact with the device.  While the unifi-os container possesses a bash binary, the base OS does not.  When writing the script, I opted for a bash based one simply because I feel more comfortable with it.  This, unfortunately, forced me to use a less-than-elegant solution where the script runs within the container and collects/delivers input/output via ssh calls to the localhost.

**Comment by pgorod** [comment]
Ah, cool. I wasn't understanding what that SSH call was doing in your script, now I know... and then you send the result back through what I assume is a host/container shared folder. 

Thanks for the script, and for your explanation.
